### ISSUE TITLE
 how fast you update you code?

### ISSUE THREAD

**Issue by Sandy4321** [shaypal5/skift#10]
cool code thanks
but when
https://github.com/facebookresearch/fastText/tree/master/python
is changes how fast you update you code?

**Comment by shaypal5** [comment]
The package automatically tests against the latest version of the official Python package, so as long as the builds pass it means no update is required. :)

**Comment by shaypal5** [comment]
Clarification: This package uses and wraps around the official `fastText` Python package, so it uses the version you have. It does **not** include a static version of the `fastText` code, so again, there's no such relation between an update of the `skift` package and the freshness of the `fastText` code it uses.
