### ISSUE TITLE
Adding model tuning.

### ISSUE THREAD

**Issue by robinicole** [shaypal5/skift#12]
The cli interface to fasttext to do parameter tuning and model quantization: 
```bash
fasttext supervised -input model_train.train -output model_tune -autotune-validation model_train.valid -autotune-modelsize 100M -autotune-duration 1200 -loss one-vs-all
```
Do you plan to implement it in your package at some point ? If I can make a pr with a piece of code that does the job

**Comment by shaypal5** [comment]
Hey @robinicole ,

First of all, of course you can make a PR! You are more than welcomed to do so. :)

Second of all, this package has the same API as the official Python one, just wraps it in a sklearn-compliant class. So if the official Python API allows this functionality using keyword arguments, so does `skift`. Have you checked it out?

**Comment by shaypal5** [comment]
I checked the issue. This is covered by Python fasttext `train_unsupervised` method, and thus can be supplied as a constructor argument to any of the `skift` wrapper classes.

For the documentation of Python fasttext's `train_unsupervised`, see here:
https://github.com/facebookresearch/fastText/blob/master/python/fasttext_module/fasttext/FastText.py#L496

**Comment by malhomaid** [comment]
I understand that I can supply `autotuneValidationFile` in `**self.kwargs` and it will be passed to `train_supervised` but `autotuneValidationFile` need to be prepared in a fasttext-compatible file.

I would love to make a PR but should I add a different function that will do fitting + autotune or add optional parameters to `fit` to enable autotuning?

**Comment by shaypal5** [comment]
Go for it!  :)

But before you start writing code, please write here an example for the API you have in mind.

Thank you for offering to contribute,
Shay

**Comment by malhomaid** [comment]
One way is to update the existing `fit` function
```
fit(self, X, y, autotune_validation_data_percentage=0):
        """Fits the classifier
        Parameters
        ----------
        X : array-like, shape = [n_samples, n_features]
            The training input samples.
        y : array-like, shape = [n_samples]
            The target values. An array of int.
        autotune_validation_data_percentage: int
             The percentage of data to be used for auto tuning fasttext parameters
```

**Comment by shaypal5** [comment]
Hmmm. Quite reasonable.

Any other sklearn classes that do that? Add optional args to `fit`?

**Comment by malhomaid** [comment]
None, as far as I know, sklearn's hyper-parameter optimizers like [GridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV) usually have `cv` arg to control the number of folds but this is not how fasttext is configured.

More options:
- `fit_autotune(self, X, y, autotune_validation_data_percentage=0)`
- `fit_autotune(self, X_train, y_train, X_validation, y_validation)` this allows the user to use custom logic to split train/validate data.
