### ISSUE TITLE
hyperparameter tuning

### ISSUE THREAD

**Issue by Alihjt** [shaypal5/skift#17]
how can we tune parameters?
in https://fasttext.cc/docs/en/autotune.html uses autotuneValidationFile to feed validation see to model. how can we set this parameter?

**Comment by shaypal5** [comment]
`skift` automatically directs all valid keyword arguments to the underlying Python API for fasttext.
Specifically, in this case the documentation states:

```python
>>> import fasttext
>>> model = fasttext.train_supervised(input='cooking.train', autotuneValidationFile='cooking.valid')
```

Which mean you can simply provide the same keyword argument to any `skift` constructor:
```python
>>> from skift import FirstColFtClassifier
>>> df = pandas.DataFrame([['woof', 0], ['meow', 1]], columns=['txt', 'lbl'])
>>> sk_clf = FirstColFtClassifier(lr=0.3, epoch=10, autotuneValidationFile='~/path/to/cooking.valid')
```

Please let me know if you encounter any issues with this!

Cheesrs, :)
Shay
