### ISSUE TITLE
Return ndarrays instead of lists while predicting

### ISSUE THREAD

**Issue by uniaz** [shaypal5/skift#2]
The functions `predict`, `predict_proba` return `lists` instead of `numpy` arrays which makes them unusable with classifiers like `sklearn.multiclass.OneVsRestClassifier`. `GridSearch` and other similar functionality also don't work.

This is a quick fix.

**Comment by shaypal5** [comment]
Hey! Good catch!

I'm assuming that you meant to write "This is a quick fix" in the pull request that will close this issue? 😄 

I'm holding my breath... ❤️

**Comment by shaypal5** [comment]
@uniaz ☝️

**Comment by uniaz** [comment]
I'm on it. Will create a PR soon.

Great repo BTW.

**Comment by shaypal5** [comment]
Closed by https://github.com/shaypal5/skift/pull/3
