### ISSUE TITLE
Testing the trained model for list of testing data instead of line by line

### ISSUE THREAD

**Issue by Maryames** [shaypal5/skift#5]
Hi,

I wanted to test my trained model and I cannot find any test method which I can easily provide the test dataset and get the results. I used ".predict" now but in that case I had to provide every test sentence separately not all together.

Really appreciate your feedback.

**Comment by shaypal5** [comment]
Hey @Maryames ! :)

Thank you for using this package.
Look again at the documentation for the `predict` method; you can definitely provide multiple samples at a single call, and get predictions for all of them:
```
"""Predict labels.
        Parameters
        ----------
        X : array-like of shape = [n_samples, n_features]
            The input samples.
        Returns
        -------
        y : array of int of shape = [n_samples]
            Predicted labels for the given inpurt samples.
        """
```

I'm closing this issue as I think this answers your question and solves your problem. If I misunderstood you, please feel free to open it again. :)
